DROP TABLE IF EXISTS Session;
DROP TABLE IF EXISTS Part;
DROP TABLE IF EXISTS Track;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS `Group`;
DROP TABLE IF EXISTS Person_Part;
DROP TABLE IF EXISTS Person_Session;
DROP TABLE IF EXISTS Data_Source;
